name: Docker Build and Push
on: [push, pull_request]

jobs:
  build:
    name: Build Image Flavour
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        include:
          - flavour: ""
            df: default
          - flavour: onbuild
            df: onbuild
          - flavour: gcloud
            df: gcloud

    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.5.0
      -
        name: Generate release tags for Docker Image
        uses: dysnix/docker-release-tags-action@master
        id: image
        with:
          image: dysnix/github-actions-runner
          release-only: false
          flavour: ${{ matrix.flavour }}
      -
        uses: docker/setup-buildx-action@v1.3.0
      -
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: env
        run: |
          if [[ -n "${{ steps.image.outputs.version }}" ]]; then
            ## Version provided by tag (i.e. it's a semver)
            #  strip -rXyz suffix
            stripped="${{ steps.image.outputs.version }}"; stripped="${stripped%-r*}"
            echo "BUILD_ARGS=RUNNER_VERSION=${stripped}" >> ${GITHUB_ENV}
          fi

      ## We use RUNNER_VERSION defined by the tag (if a valid semver is given)
      -
        name: Build and push
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          file: ./Dockerfile.${{ matrix.df }}
          push: ${{ steps.image.outputs.runsOnTag }}
          tags: ${{ steps.image.outputs.images }}
          build-args: ${{ env.BUILD_ARGS }}
