name: Docker Image CI
on: [push, pull_request]

jobs:
  build:
    name: Build Image Flavour
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        include:
          - flavour: default
          - flavour: onbuild
          - flavour: gcloud

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: services1dysnix
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: oprypin/find-latest-tag@v1
        id: latestRunner
        with:
          repository: actions/runner

      - id: release
        run: |
          latest_tag="${{ matrix.flavour }}"
          if [[ "$latest_tag" == "default" ]]; then latest_tag=latest; fi

          echo "::set-output latest_tag=$latest_tag"

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.${{ matrix.flavour }}
          push: false

          tags: |
            dysnix/github-actions-runner:${{ steps.latestRunner.outputs.tag }}
